#!/bin/sh

emacsprog="${PVSEMACS-emacs}"

echo "Launcher scripts are relocatable; no PVSPATH rewrite is needed."

# Take care of Catalina quarantine issues
if [ `uname -s` = "Darwin" ]; then
  echo "\nCalling xattr to remove MacOSX quarantine attributes on files"
  xattr -r -d com.apple.quarantine . 2> /dev/null
fi

# Byte compile emacs

emacsinfo="`which $emacsprog`: `$emacsprog --version | head -n 1`"
echo "\nByte compiling emacs files using $emacsinfo"
echo "  if this is not the right Emacs, set PVSEMACS"
echo "  otherwise the byte compiled files will cause an error"
echo "see byte-compile.log for details (mostly warnings)"
echo "Byte compilation currently generates lots of warnings" > byte-compile.log
echo "  (because of compatibility issues with older Emacs versions)\n" >> byte-compile.log
(cd emacs; $emacsprog -batch -l pvs-byte-compile.el) \
    >> byte-compile.log 2>&1 \
    || echo "!!! Something went wrong - see the end of byte-compile.log"
