const char *yices_version;
const char *yices_build_arch;
const char *yices_build_mode;
const char *yices_build_date;
int32_t yices_has_mcsat(void);
int32_t yices_is_thread_safe(void);
void yices_init(void);
void yices_exit(void);
void yices_reset(void);
void yices_free_string(char *s);
void yices_set_out_of_mem_callback(void (*callback)(void));
error_code_t yices_error_code(void);
error_report_t *yices_error_report(void);
void yices_clear_error(void);
int32_t yices_print_error(FILE *f);
int32_t yices_print_error_fd(int fd);
char *yices_error_string(void);
void yices_init_term_vector(term_vector_t *v);
void yices_init_type_vector(type_vector_t *v);
void yices_delete_term_vector(term_vector_t *v);
void yices_delete_type_vector(type_vector_t *v);
void yices_reset_term_vector(term_vector_t *v);
void yices_reset_type_vector(type_vector_t *v);
type_t yices_bool_type(void);
type_t yices_int_type(void);
type_t yices_real_type(void);
type_t yices_bv_type(uint32_t size);
type_t yices_new_scalar_type(uint32_t card);
type_t yices_new_uninterpreted_type(void);
type_t yices_tuple_type(uint32_t n, const type_t tau[]);
type_t yices_tuple_type1(type_t tau1);
type_t yices_tuple_type2(type_t tau1, type_t tau2);
type_t yices_tuple_type3(type_t tau1, type_t tau2, type_t tau3);
type_t yices_function_type(uint32_t n, const type_t dom[], type_t range);
type_t yices_function_type1(type_t tau1, type_t range);
type_t yices_function_type2(type_t tau1, type_t tau2, type_t range);
type_t yices_function_type3(type_t tau1, type_t tau2, type_t tau3, type_t range);
type_t yices_type_variable(uint32_t id);
int32_t yices_type_constructor(const char *name, uint32_t n);
int32_t yices_type_macro(const char *name, uint32_t n, type_t *vars, type_t body);
type_t yices_instance_type(int32_t cid, uint32_t n, type_t tau[]);
int32_t yices_get_macro_by_name(const char *name);
void yices_remove_type_macro_name(const char *name);
void yices_delete_type_macro(int32_t id);
int32_t yices_type_is_bool(type_t tau);
int32_t yices_type_is_int(type_t tau);
int32_t yices_type_is_real(type_t tau);
int32_t yices_type_is_arithmetic(type_t tau);
int32_t yices_type_is_bitvector(type_t tau);
int32_t yices_type_is_tuple(type_t tau);
int32_t yices_type_is_function(type_t tau);
int32_t yices_type_is_scalar(type_t tau);
int32_t yices_type_is_uninterpreted(type_t tau);
int32_t yices_test_subtype(type_t tau, type_t sigma);
int32_t yices_compatible_types(type_t tau, type_t sigma);
uint32_t yices_bvtype_size(type_t tau);
uint32_t yices_scalar_type_card(type_t tau);
int32_t yices_type_num_children(type_t tau);
type_t yices_type_child(type_t tau, int32_t i);
int32_t yices_type_children(type_t tau, type_vector_t *v);
term_t yices_true(void);
term_t yices_false(void);
term_t yices_constant(type_t tau, int32_t index);
term_t yices_new_uninterpreted_term(type_t tau);
term_t yices_new_variable(type_t tau);
term_t yices_application(term_t fun, uint32_t n, const term_t arg[]);
term_t yices_application1(term_t fun, term_t arg1);
term_t yices_application2(term_t fun, term_t arg1, term_t arg2);
term_t yices_application3(term_t fun, term_t arg1, term_t arg2, term_t arg3);
term_t yices_ite(term_t cond, term_t then_term, term_t else_term);
term_t yices_eq(term_t left, term_t right);
term_t yices_neq(term_t left, term_t right);
term_t yices_not(term_t arg);
term_t yices_or(uint32_t n, term_t arg[]);
term_t yices_and(uint32_t n, term_t arg[]);
term_t yices_xor(uint32_t n, term_t arg[]);
term_t yices_or2(term_t t1, term_t t2);
term_t yices_and2(term_t t1, term_t t2);
term_t yices_xor2(term_t t1, term_t t2);
term_t yices_or3(term_t t1, term_t t2, term_t t3);
term_t yices_and3(term_t t1, term_t t2, term_t t3);
term_t yices_xor3(term_t t1, term_t t2, term_t t3);
term_t yices_iff(term_t left, term_t right);
term_t yices_implies(term_t left, term_t right);
term_t yices_tuple(uint32_t n, const term_t arg[]);
term_t yices_pair(term_t arg1, term_t arg2);
term_t yices_triple(term_t arg1, term_t arg2, term_t arg3);
term_t yices_select(uint32_t index, term_t tuple);
term_t yices_tuple_update(term_t tuple, uint32_t index, term_t new_v);
term_t yices_update(term_t fun, uint32_t n, const term_t arg[], term_t new_v);
term_t yices_update1(term_t fun, term_t arg1, term_t new_v);
term_t yices_update2(term_t fun, term_t arg1, term_t arg2, term_t new_v);
term_t yices_update3(term_t fun, term_t arg1, term_t arg2, term_t arg3, term_t new_v);
term_t yices_distinct(uint32_t n, term_t arg[]);
term_t yices_forall(uint32_t n, term_t var[], term_t body);
term_t yices_exists(uint32_t n, term_t var[], term_t body);
term_t yices_lambda(uint32_t n, const term_t var[], term_t body);
term_t yices_zero(void);
term_t yices_int32(int32_t val);
term_t yices_int64(int64_t val);
term_t yices_rational32(int32_t num, uint32_t den);
term_t yices_rational64(int64_t num, uint64_t den);
term_t yices_mpz(const mpz_t z);
term_t yices_mpq(const mpq_t q);
term_t yices_parse_rational(const char *s);
term_t yices_parse_float(const char *s);
term_t yices_add(term_t t1, term_t t2);
term_t yices_sub(term_t t1, term_t t2);
term_t yices_neg(term_t t1);
term_t yices_mul(term_t t1, term_t t2);
term_t yices_square(term_t t1);
term_t yices_power(term_t t1, uint32_t d);
term_t yices_sum(uint32_t n, const term_t t[]);
term_t yices_product(uint32_t n, const term_t t[]);
term_t yices_division(term_t t1, term_t t2);
term_t yices_idiv(term_t t1, term_t t2);
term_t yices_imod(term_t t1, term_t t2);
term_t yices_divides_atom(term_t t1, term_t t2);
term_t yices_is_int_atom(term_t t);
term_t yices_abs(term_t t);
term_t yices_floor(term_t t);
term_t yices_ceil(term_t t);
term_t yices_poly_int32(uint32_t n, const int32_t a[], const term_t t[]);
term_t yices_poly_int64(uint32_t n, const int64_t a[], const term_t t[]);
term_t yices_poly_rational32(uint32_t n, const int32_t num[], const uint32_t den[], const term_t t[]);
term_t yices_poly_rational64(uint32_t n, const int64_t num[], const uint64_t den[], const term_t t[]);
term_t yices_poly_mpz(uint32_t n, const mpz_t z[], const term_t t[]);
term_t yices_poly_mpq(uint32_t n, const mpq_t q[], const term_t t[]);
term_t yices_arith_eq_atom(term_t t1, term_t t2);
term_t yices_arith_neq_atom(term_t t1, term_t t2);
term_t yices_arith_geq_atom(term_t t1, term_t t2);
term_t yices_arith_leq_atom(term_t t1, term_t t2);
term_t yices_arith_gt_atom(term_t t1, term_t t2);
term_t yices_arith_lt_atom(term_t t1, term_t t2);
term_t yices_arith_eq0_atom(term_t t);
term_t yices_arith_neq0_atom(term_t t);
term_t yices_arith_geq0_atom(term_t t);
term_t yices_arith_leq0_atom(term_t t);
term_t yices_arith_gt0_atom(term_t t);
term_t yices_arith_lt0_atom(term_t t);
term_t yices_bvconst_uint32(uint32_t n, uint32_t x);
term_t yices_bvconst_uint64(uint32_t n, uint64_t x);
term_t yices_bvconst_int32(uint32_t n, int32_t x);
term_t yices_bvconst_int64(uint32_t n, int64_t x);
term_t yices_bvconst_mpz(uint32_t n, const mpz_t x);
term_t yices_bvconst_zero(uint32_t n);
term_t yices_bvconst_one(uint32_t n);
term_t yices_bvconst_minus_one(uint32_t n);
term_t yices_bvconst_from_array(uint32_t n, const int32_t a[]);
term_t yices_parse_bvbin(const char *s);
term_t yices_parse_bvhex(const char *s);
term_t yices_bvadd(term_t t1, term_t t2);
term_t yices_bvsub(term_t t1, term_t t2);
term_t yices_bvneg(term_t t1);
term_t yices_bvmul(term_t t1, term_t t2);
term_t yices_bvsquare(term_t t1);
term_t yices_bvpower(term_t t1, uint32_t d);
term_t yices_bvdiv(term_t t1, term_t t2);
term_t yices_bvrem(term_t t1, term_t t2);
term_t yices_bvsdiv(term_t t1, term_t t2);
term_t yices_bvsrem(term_t t1, term_t t2);
term_t yices_bvsmod(term_t t1, term_t t2);
term_t yices_bvnot(term_t t1);
term_t yices_bvnand(term_t t1, term_t t2);
term_t yices_bvnor(term_t t1, term_t t2);
term_t yices_bvxnor(term_t t1, term_t t2);
term_t yices_bvshl(term_t t1, term_t t2);
term_t yices_bvlshr(term_t t1, term_t t2);
term_t yices_bvashr(term_t t1, term_t t2);
term_t yices_bvand(uint32_t n, const term_t t[]);
term_t yices_bvor(uint32_t n, const term_t t[]);
term_t yices_bvxor(uint32_t n, const term_t t[]);
term_t yices_bvand2(term_t t1, term_t t2);
term_t yices_bvor2(term_t t1, term_t t2);
term_t yices_bvxor2(term_t t1, term_t t2);
term_t yices_bvand3(term_t t1, term_t t2, term_t t3);
term_t yices_bvor3(term_t t1, term_t t2, term_t t3);
term_t yices_bvxor3(term_t t1, term_t t2, term_t t3);
term_t yices_bvsum(uint32_t n, const term_t t[]);
term_t yices_bvproduct(uint32_t n, const term_t t[]);
term_t yices_shift_left0(term_t t, uint32_t n);
term_t yices_shift_left1(term_t t, uint32_t n);
term_t yices_shift_right0(term_t t, uint32_t n);
term_t yices_shift_right1(term_t t, uint32_t n);
term_t yices_ashift_right(term_t t, uint32_t n);
term_t yices_rotate_left(term_t t, uint32_t n);
term_t yices_rotate_right(term_t t, uint32_t n);
term_t yices_bvextract(term_t t, uint32_t i, uint32_t j);
term_t yices_bvconcat2(term_t t1, term_t t2);
term_t yices_bvconcat(uint32_t n, const term_t t[]);
term_t yices_bvrepeat(term_t t, uint32_t n);
term_t yices_sign_extend(term_t t, uint32_t n);
term_t yices_zero_extend(term_t t, uint32_t n);
term_t yices_redand(term_t t);
term_t yices_redor(term_t t);
term_t yices_redcomp(term_t t1, term_t t2);
term_t yices_bvarray(uint32_t n, const term_t arg[]);
term_t yices_bitextract(term_t t, uint32_t i);
term_t yices_bveq_atom(term_t t1, term_t t2);
term_t yices_bvneq_atom(term_t t1, term_t t2);
term_t yices_bvge_atom(term_t t1, term_t t2);
term_t yices_bvgt_atom(term_t t1, term_t t2);
term_t yices_bvle_atom(term_t t1, term_t t2);
term_t yices_bvlt_atom(term_t t1, term_t t2);
term_t yices_bvsge_atom(term_t t1, term_t t2);
term_t yices_bvsgt_atom(term_t t1, term_t t2);
term_t yices_bvsle_atom(term_t t1, term_t t2);
term_t yices_bvslt_atom(term_t t1, term_t t2);
type_t yices_parse_type(const char *s);
term_t yices_parse_term(const char *s);
term_t yices_subst_term(uint32_t n, const term_t var[], const term_t map[], term_t t);
int32_t yices_subst_term_array(uint32_t n, const term_t var[], const term_t map[], uint32_t m, term_t t[]);
int32_t yices_set_type_name(type_t tau, const char *name);
int32_t yices_set_term_name(term_t t, const char *name);
void yices_remove_type_name(const char *name);
void yices_remove_term_name(const char *name);
type_t yices_get_type_by_name(const char *name);
term_t yices_get_term_by_name(const char *name);
int32_t yices_clear_type_name(type_t tau);
int32_t yices_clear_term_name(term_t t);
const char *yices_get_type_name(type_t tau);
const char *yices_get_term_name(term_t t);
type_t yices_type_of_term(term_t t);
int32_t yices_term_is_bool(term_t t);
int32_t yices_term_is_int(term_t t);
int32_t yices_term_is_real(term_t t);
int32_t yices_term_is_arithmetic(term_t t);
int32_t yices_term_is_bitvector(term_t t);
int32_t yices_term_is_tuple(term_t t);
int32_t yices_term_is_function(term_t t);
int32_t yices_term_is_scalar(term_t t);
uint32_t yices_term_bitsize(term_t t);
int32_t yices_term_is_ground(term_t t);
int32_t yices_term_is_atomic(term_t t);
int32_t yices_term_is_composite(term_t t);
int32_t yices_term_is_projection(term_t t);
int32_t yices_term_is_sum(term_t t);
int32_t yices_term_is_bvsum(term_t t);
int32_t yices_term_is_product(term_t t);
term_constructor_t yices_term_constructor(term_t t);
int32_t yices_term_num_children(term_t t);
term_t yices_term_child(term_t t, int32_t i);
int32_t yices_term_children(term_t t, term_vector_t *v);
int32_t yices_proj_index(term_t t);
term_t yices_proj_arg(term_t t);
int32_t yices_bool_const_value(term_t t, int32_t *val);
int32_t yices_bv_const_value(term_t t, int32_t val[]);
int32_t yices_scalar_const_value(term_t t, int32_t *val);
int32_t yices_rational_const_value(term_t t, mpq_t q);
int32_t yices_finitefield_const_value(term_t t, mpz_t z);
int32_t yices_sum_component(term_t t, int32_t i, mpq_t coeff, term_t *term);
int32_t yices_bvsum_component(term_t t, int32_t i, int32_t val[], term_t *term);
int32_t yices_product_component(term_t t, int32_t i, term_t *term, uint32_t *exp);
uint32_t yices_num_terms(void);
uint32_t yices_num_types(void);
int32_t yices_incref_term(term_t t);
int32_t yices_decref_term(term_t t);
int32_t yices_incref_type(type_t tau);
int32_t yices_decref_type(type_t tau);
uint32_t yices_num_posref_terms(void);
uint32_t yices_num_posref_types(void);
void yices_garbage_collect(const term_t t[], uint32_t nt, const type_t tau[], uint32_t ntau, int32_t keep_named);
ctx_config_t *yices_new_config(void);
void yices_free_config(ctx_config_t *config);
int32_t yices_set_config(ctx_config_t *config, const char *name, const char *value);
int32_t yices_default_config_for_logic(ctx_config_t *config, const char *logic);
context_t *yices_new_context(const ctx_config_t *config);
void yices_free_context(context_t *ctx);
smt_status_t yices_context_status(context_t *ctx);
void yices_reset_context(context_t *ctx);
int32_t yices_push(context_t *ctx);
int32_t yices_pop(context_t *ctx);
int32_t yices_context_enable_option(context_t *ctx, const char *option);
int32_t yices_context_disable_option(context_t *ctx, const char *option);
int32_t yices_assert_formula(context_t *ctx, term_t t);
int32_t yices_assert_formulas(context_t *ctx, uint32_t n, const term_t t[]);
smt_status_t yices_check_context(context_t *ctx, const param_t *params);
smt_status_t yices_check_context_with_assumptions(context_t *ctx, const param_t *params, uint32_t n, const term_t t[]);
smt_status_t yices_check_context_with_model(context_t *ctx, const param_t *params, model_t *mdl, uint32_t n, const term_t t[]);
smt_status_t yices_check_context_with_model_and_hint(context_t *ctx, const param_t *params, model_t *mdl, uint32_t n, const term_t t[], uint32_t m);
smt_status_t yices_mcsat_set_fixed_var_order(context_t *ctx, uint32_t n, const term_t t[]);
smt_status_t yices_mcsat_set_initial_var_order(context_t *ctx, uint32_t n, const term_t t[]);
smt_status_t yices_check_context_with_interpolation(interpolation_context_t *ctx, const param_t *params, int32_t build_model);
int32_t yices_assert_blocking_clause(context_t *ctx);
void yices_stop_search(context_t *ctx);
param_t *yices_new_param_record(void);
void yices_default_params_for_context(const context_t *ctx, param_t *params);
int32_t yices_set_param(param_t *p, const char *pname, const char *value);
void yices_free_param_record(param_t *param);
int32_t yices_get_unsat_core(context_t *ctx, term_vector_t *v);
term_t yices_get_model_interpolant(context_t *ctx);
model_t *yices_get_model(context_t *ctx, int32_t keep_subst);
void yices_free_model(model_t *mdl);
model_t *yices_new_model(void);
model_t *yices_model_from_map(uint32_t n, const term_t var[], const term_t map[]);
int32_t yices_model_set_bool(model_t *model, term_t var, int32_t val);
int32_t yices_model_set_int32(model_t *model, term_t var, int32_t val);
int32_t yices_model_set_int64(model_t *model, term_t var, int64_t val);
int32_t yices_model_set_rational32(model_t *model, term_t var, int32_t num, uint32_t den);
int32_t yices_model_set_rational64(model_t *model, term_t var, int64_t num, uint64_t den);
int32_t yices_model_set_mpz(model_t *model, term_t var, mpz_t val);
int32_t yices_model_set_mpq(model_t *model, term_t var, mpq_t val);
int32_t yices_model_set_algebraic_number(model_t *model, term_t var, const lp_algebraic_number_t *val);
int32_t yices_model_set_bv_int32(model_t *model, term_t var, int32_t val);
int32_t yices_model_set_bv_int64(model_t *model, term_t var, int64_t val);
int32_t yices_model_set_bv_uint32(model_t *model, term_t var, uint32_t val);
int32_t yices_model_set_bv_uint64(model_t *model, term_t var, uint64_t val);
int32_t yices_model_set_bv_mpz(model_t *model, term_t var, mpz_t val);
int32_t yices_model_set_bv_from_array(model_t *model, term_t var, uint32_t n, const int32_t a[]);
int32_t yices_model_set_scalar(model_t *model, term_t var, int32_t val);
int32_t yices_model_set_double(model_t *model, term_t var, double val);
int32_t yices_model_set_float(model_t *model, term_t var, float val);
void yices_model_collect_defined_terms(model_t *mdl, term_vector_t *v);
smt_status_t yices_check_formula(term_t f, const char *logic, model_t **model, const char *delegate);
smt_status_t yices_check_formulas(const term_t f[], uint32_t n, const char *logic, model_t **model, const char *delegate);
int32_t yices_has_delegate(const char *delegate);
int32_t yices_export_formula_to_dimacs(term_t f, const char *filename, int32_t simplify_cnf, smt_status_t *status);
int32_t yices_export_formulas_to_dimacs(const term_t f[], uint32_t n, const char *filename, int32_t simplify_cnf, smt_status_t *status);
int32_t yices_get_bool_value(model_t *mdl, term_t t, int32_t *val);
int32_t yices_get_int32_value(model_t *mdl, term_t t, int32_t *val);
int32_t yices_get_int64_value(model_t *mdl, term_t t, int64_t *val);
int32_t yices_get_rational32_value(model_t *mdl, term_t t, int32_t *num, uint32_t *den);
int32_t yices_get_rational64_value(model_t *mdl, term_t t, int64_t *num, uint64_t *den);
int32_t yices_get_double_value(model_t *mdl, term_t t, double *val);
int32_t yices_get_mpz_value(model_t *mdl, term_t t, mpz_t val);
int32_t yices_get_mpq_value(model_t *mdl, term_t t, mpq_t val);
int32_t yices_get_algebraic_number_value(model_t *mdl, term_t t, lp_algebraic_number_t *a);
int32_t yices_get_bv_value(model_t *mdl, term_t t, int32_t val[]);
int32_t yices_get_scalar_value(model_t *mdl, term_t t, int32_t *val);
void yices_init_yval_vector(yval_vector_t *v);
void yices_delete_yval_vector(yval_vector_t *v);
void yices_reset_yval_vector(yval_vector_t *v);
int32_t yices_get_value(model_t *mdl, term_t t, yval_t *val);
int32_t yices_val_is_int32(model_t *mdl, const yval_t *v);
int32_t yices_val_is_int64(model_t *mdl, const yval_t *v);
int32_t yices_val_is_rational32(model_t *mdl, const yval_t *v);
int32_t yices_val_is_rational64(model_t *mdl, const yval_t *v);
int32_t yices_val_is_integer(model_t *mdl, const yval_t *v);
uint32_t yices_val_bitsize(model_t *mdl, const yval_t *v);
uint32_t yices_val_tuple_arity(model_t *mdl, const yval_t *v);
uint32_t yices_val_mapping_arity(model_t *mdl, const yval_t *v);
uint32_t yices_val_function_arity(model_t *mdl, const yval_t *v);
type_t yices_val_function_type(model_t *mdl, const yval_t *v);
int32_t yices_val_get_bool(model_t *mdl, const yval_t *v, int32_t *val);
int32_t yices_val_get_int32(model_t *mdl, const yval_t *v, int32_t *val);
int32_t yices_val_get_int64(model_t *mdl, const yval_t *v, int64_t *val);
int32_t yices_val_get_rational32(model_t *mdl, const yval_t *v, int32_t *num, uint32_t *den);
int32_t yices_val_get_rational64(model_t *mdl, const yval_t *v, int64_t *num, uint64_t *den);
int32_t yices_val_get_double(model_t *mdl, const yval_t *v, double *val);
int32_t yices_val_get_mpz(model_t *mdl, const yval_t *v, mpz_t val);
int32_t yices_val_get_mpq(model_t *mdl, const yval_t *v, mpq_t val);
int32_t yices_val_get_algebraic_number(model_t *mdl, const yval_t *v, lp_algebraic_number_t *a);
int32_t yices_val_get_bv(model_t *mdl, const yval_t *v, int32_t val[]);
int32_t yices_val_get_scalar(model_t *mdl, const yval_t *v, int32_t *val, type_t *tau);
int32_t yices_val_expand_tuple(model_t *mdl, const yval_t *v, yval_t child[]);
int32_t yices_val_expand_function(model_t *mdl, const yval_t *f, yval_t *def, yval_vector_t *v);
int32_t yices_val_expand_mapping(model_t *mdl, const yval_t *m, yval_t tup[], yval_t *val);
int32_t yices_formula_true_in_model(model_t *mdl, term_t f);
int32_t yices_formulas_true_in_model(model_t *mdl, uint32_t n, const term_t f[]);
term_t yices_get_value_as_term(model_t *mdl, term_t t);
int32_t yices_term_array_value(model_t *mdl, uint32_t n, const term_t a[], term_t b[]);
int32_t yices_model_term_support(model_t *mdl, term_t t, term_vector_t *v);
int32_t yices_model_term_array_support(model_t *mdl, uint32_t n, const term_t a[], term_vector_t *v);
int32_t yices_implicant_for_formula(model_t *mdl, term_t t, term_vector_t *v);
int32_t yices_implicant_for_formulas(model_t *mdl, uint32_t n, const term_t a[], term_vector_t *v);
int32_t yices_generalize_model(model_t *mdl, term_t t, uint32_t nelims, const term_t elim[], yices_gen_mode_t mode, term_vector_t *v);
int32_t yices_generalize_model_array(model_t *mdl, uint32_t n, const term_t a[], uint32_t nelims, const term_t elim[], yices_gen_mode_t mode, term_vector_t *v);
int32_t yices_pp_type(FILE *f, type_t tau, uint32_t width, uint32_t height, uint32_t offset);
int32_t yices_pp_term(FILE *f, term_t t, uint32_t width, uint32_t height, uint32_t offset);
int32_t yices_pp_term_array(FILE *f, uint32_t n, const term_t a[], uint32_t width, uint32_t height, uint32_t offset, int32_t horiz);
void yices_print_model(FILE *f, model_t *mdl);
int32_t yices_pp_model(FILE *f, model_t *mdl, uint32_t width, uint32_t height, uint32_t offset);
int32_t yices_print_term_values(FILE *f, model_t *mdl, uint32_t n, const term_t a[]);
int32_t yices_pp_term_values(FILE *f, model_t *mdl, uint32_t n, const term_t a[], uint32_t width, uint32_t height, uint32_t offset);
int32_t yices_pp_type_fd(int fd, type_t tau, uint32_t width, uint32_t height, uint32_t offset);
int32_t yices_pp_term_fd(int fd, term_t t, uint32_t width, uint32_t height, uint32_t offset);
int32_t yices_pp_term_array_fd(int fd, uint32_t n, const term_t a[], uint32_t width, uint32_t height, uint32_t offset, int32_t horiz);
int32_t yices_print_model_fd(int fd, model_t *mdl);
int32_t yices_pp_model_fd(int fd, model_t *mdl, uint32_t width, uint32_t height, uint32_t offset);
int32_t yices_print_term_values_fd(int fd, model_t *mdl, uint32_t n, const term_t a[]);
int32_t yices_pp_term_values_fd(int fd, model_t *mdl, uint32_t n, const term_t a[], uint32_t width, uint32_t height, uint32_t offset);
char *yices_type_to_string(type_t tau, uint32_t width, uint32_t height, uint32_t offset);
char *yices_term_to_string(term_t t, uint32_t width, uint32_t height, uint32_t offset);
char *yices_model_to_string(model_t *mdl, uint32_t width, uint32_t height, uint32_t offset);
int32_t yices_model_set_term(model_t *model, term_t var, term_t value);
int32_t yices_model_set_yval(model_t *model, term_t var, const yval_t *yval);
int32_t yices_model_make_tuple(model_t *model, uint32_t n, const yval_t elem[], yval_t *tuple);
int32_t yices_model_set_tuple(model_t *model, term_t var, uint32_t n, const yval_t elem[]);
int32_t yices_model_make_mapping(model_t *model, uint32_t arity, const yval_t args[], const yval_t *value, yval_t *mapping);
int32_t yices_model_make_function(model_t *model, type_t fun_type, uint32_t n, const yval_t mappings[], const yval_t *def, yval_t *fun);
int32_t yices_model_set_function(model_t *model, term_t var, uint32_t n, const yval_t mappings[], const yval_t *def);
